const DATA_URL = '../data/canonical/all-tasks.jsonl';
const DOMAINS_URL = '../data/canonical/domains.json';
const REPOSITORY = 'https://github.com/KalarisLabs/Myriad';
const PAGE_SIZE = 50;
const searchInput = document.querySelector('#search'), domainSelect = document.querySelector('#domain'), workstreamSelect = document.querySelector('#workstream'), resultsElement = document.querySelector('#results'), summaryElement = document.querySelector('#result-summary'), moreButton = document.querySelector('#more'), exportButton = document.querySelector('#export'), dialog = document.querySelector('#task-dialog'), detail = document.querySelector('#task-detail'), template = document.querySelector('#result-template');
let tasks = [], domains = [], shown = PAGE_SIZE, filtered = [];
const taskUrl = (task) => `${REPOSITORY}/blob/main/myriad/domains/${task.domain_code}-${task.domain_slug}/nodes/${task.id}.md`;
const cliCommand = (task) => `npx kalaris-myriad show ${task.id} --json`;
function matchingTasks() { const terms = searchInput.value.trim().toLowerCase().split(/\s+/).filter(Boolean); return tasks.filter((task) => { if (domainSelect.value && task.domain_id !== Number(domainSelect.value)) return false; if (workstreamSelect.value && task.workstream_index !== Number(workstreamSelect.value)) return false; const haystack = [task.goal, task.objective, task.routing.name, task.routing.description, task.routing.keywords.join(' ')].join(' ').toLowerCase(); return terms.every((term) => haystack.includes(term)); }); }
function render() { filtered = matchingTasks(); const visible = filtered.slice(0, shown); resultsElement.replaceChildren(); for (const task of visible) { const card = template.content.firstElementChild.cloneNode(true); card.querySelector('.task-id').textContent = task.id; card.querySelector('.task-title').textContent = task.goal; card.querySelector('.task-meta').textContent = `${task.domain} · ${task.workstream}`; card.addEventListener('click', () => openTask(task)); resultsElement.append(card); } summaryElement.textContent = filtered.length === tasks.length ? `Showing ${visible.length.toLocaleString()} of all ${tasks.length.toLocaleString()} task nodes` : `${filtered.length.toLocaleString()} matching task node${filtered.length === 1 ? '' : 's'} · showing ${visible.length.toLocaleString()}`; moreButton.hidden = visible.length >= filtered.length; exportButton.disabled = filtered.length === 0; }
function populateWorkstreams() { const selected = domains.find((domain) => domain.domain_id === Number(domainSelect.value)); workstreamSelect.replaceChildren(new Option('All workstreams', '')); if (!selected) { workstreamSelect.disabled = true; return; } for (const workstream of selected.workstreams) workstreamSelect.add(new Option(`${workstream.index}. ${workstream.name}`, workstream.index)); workstreamSelect.disabled = false; }
function copyButton(label, value) { const button = document.createElement('button'); button.type = 'button'; button.className = 'copy'; button.textContent = label; button.addEventListener('click', async () => { try { await navigator.clipboard.writeText(value); button.textContent = 'Copied'; setTimeout(() => { button.textContent = label; }, 1400); } catch { window.prompt('Copy this value:', value); } }); return button; }
function field(label, value) { const section = document.createElement('section'), heading = document.createElement('h3'), body = document.createElement('p'); heading.textContent = label; body.textContent = value; section.append(heading, body); return section; }
function openTask(task, updateHash = true) { if (updateHash) history.replaceState(null, '', `#${task.id}`); detail.replaceChildren(); const eyebrow = document.createElement('p'), title = document.createElement('h2'), route = document.createElement('p'), actions = document.createElement('div'); eyebrow.className = 'eyebrow'; eyebrow.textContent = `${task.id} · ${task.domain_code}`; title.id = 'dialog-title'; title.textContent = task.goal; route.className = 'route'; route.textContent = task.routing.name; actions.className = 'actions'; actions.append(copyButton('Copy task ID', task.id), copyButton('Copy CLI command', cliCommand(task))); const source = document.createElement('a'); source.href = taskUrl(task); source.target = '_blank'; source.rel = 'noreferrer'; source.textContent = 'Open canonical GitHub source ↗'; actions.append(source); detail.append(eyebrow, title, route, actions, field('Objective', task.objective), field('Domain', task.domain), field('Workstream', task.workstream), field('Maturity', `${task.maturity.status} — ${task.maturity.operational_readiness}`)); const safety = field('Safety and review boundary', `Mode: ${task.execution_contract.mode}. Qualified human review: required. No-call when inputs or provenance are missing, evidence conflicts materially, applicability is unsupported, or the request exceeds computational-advisory scope.`); safety.className = 'safety'; detail.append(safety); if (!dialog.open) dialog.showModal(); }
function exportFiltered() { const url = URL.createObjectURL(new Blob([JSON.stringify(filtered, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'myriad-explorer-results.json'; link.click(); URL.revokeObjectURL(url); }
searchInput.addEventListener('input', () => { shown = PAGE_SIZE; render(); }); domainSelect.addEventListener('change', () => { workstreamSelect.value = ''; populateWorkstreams(); shown = PAGE_SIZE; render(); }); workstreamSelect.addEventListener('change', () => { shown = PAGE_SIZE; render(); }); document.querySelector('#clear').addEventListener('click', () => { searchInput.value = ''; domainSelect.value = ''; workstreamSelect.value = ''; populateWorkstreams(); shown = PAGE_SIZE; render(); searchInput.focus(); }); moreButton.addEventListener('click', () => { shown += PAGE_SIZE; render(); }); exportButton.addEventListener('click', exportFiltered); dialog.addEventListener('close', () => history.replaceState(null, '', `${location.pathname}${location.search}`)); window.addEventListener('hashchange', () => { const task = tasks.find((item) => item.id === location.hash.slice(1)); if (task) openTask(task, false); });
async function init() { try { const [domainResponse, taskResponse] = await Promise.all([fetch(DOMAINS_URL), fetch(DATA_URL)]); if (!domainResponse.ok || !taskResponse.ok) throw new Error('Canonical data could not be loaded. Start the explorer with `npm run explorer`.'); domains = await domainResponse.json(); tasks = (await taskResponse.text()).trim().split('\n').filter(Boolean).map(JSON.parse); for (const domain of domains) domainSelect.add(new Option(`${domain.domain_code} · ${domain.name}`, domain.domain_id)); document.querySelector('#task-count').textContent = tasks.length.toLocaleString(); render(); const task = tasks.find((item) => item.id === location.hash.slice(1)); if (task) openTask(task, false); } catch (error) { summaryElement.textContent = error.message; } }
init();
